import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

const INR_RATE = 1;

const convertPriceToINR = (price) => {
  const numericPrice = parseFloat(String(price).replace(/[^0-9.]/g, "")) || 0;
  const converted = Math.round(numericPrice * INR_RATE * 100) / 100;
  return converted.toFixed(2);
};

const convertProducts = (items) =>
  items.map((item) => ({
    ...item,
    price: convertPriceToINR(item.price),
  }));

const expandCategoryItems = (items, targetCount = 100) => {
  const byCategory = items.reduce((acc, item) => {
    const category = item.category || "Others";
    if (!acc[category]) acc[category] = [];
    acc[category].push(item);
    return acc;
  }, {});

  const expanded = [];

  Object.entries(byCategory).forEach(([category, categoryItems]) => {
    const baseCount = categoryItems.length;
    categoryItems.forEach((item) => expanded.push(item));

    let cloneIndex = 1;
    while (expanded.filter((entry) => entry.category === category).length < targetCount) {
      const original = categoryItems[(cloneIndex - 1) % baseCount];
      expanded.push({
        ...original,
        _id: original._id * 1000 + cloneIndex,
        productName: `${original.productName} ${cloneIndex}`,
      });
      cloneIndex += 1;
    }
  });

  return expanded;
};

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
const baseSplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Cap for Boys",
    price: "350.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Tea Table",
    price: "1800.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Headphones",
    price: "250.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Sun glasses",
    price: "2200.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
// =================== Special Offer data End here ==============
export const SplOfferData = convertProducts(baseSplOfferData);

// =================== PaginationItems Start here ===============

const basePaginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    category: "Accessories",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "Tea Table",
    price: "1800.00",
    color: "Gray",
    badge: true,
    category: "Furniture",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "Headphones",
    price: "250.00",
    color: "Mixed",
    badge: true,
    category: "Electronics",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1004,
    img: spfFour,
    productName: "Sun glasses",
    price: "2200.00",
    color: "Black",
    badge: true,
    category: "Accessories",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "350.00",
    color: "Blank and White",
    badge: true,
    category: "Home & Garden",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "New Backpack",
    price: "1800.00",
    color: "Gray",
    badge: false,
    category: "Bags",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Household materials",
    price: "250.00",
    color: "Mixed",
    badge: true,
    category: "Home & Garden",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "2200.00",
    color: "Black",
    badge: false,
    category: "Bags",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "440.00",
    color: "Black",
    badge: true,
    category: "Home & Garden",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "2500.00",
    color: "Black",
    badge: true,
    category: "Electronics",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1011,
    img: newArrThree,
    productName: "cloth Basket",
    price: "800.00",
    color: "Mixed",
    badge: true,
    category: "Home & Garden",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "600.00",
    color: "Mixed",
    badge: false,
    category: "Toys & Games",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1013,
    img: newArrTwo,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    category: "Toys & Games",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },

  {
    _id: 1014,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    category: "Electronics",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1015,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    category: "Toys & Games",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1016,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    category: "Electronics",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1017,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "2200.00",
    color: "Black",
    badge: false,
    category: "Bags",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1018,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "440.00",
    color: "Black",
    badge: true,
    category: "Home & Garden",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1019,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "2500.00",
    color: "Black",
    badge: true,
    category: "Electronics",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1020,
    img: newArrThree,
    productName: "cloth Basket",
    price: "800.00",
    color: "Mixed",
    badge: true,
    category: "Home & Garden",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1021,
    img: spfThree,
    productName: "Headphones",
    price: "250.00",
    color: "Mixed",
    badge: true,
    category: "Electronics",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1022,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    category: "Accessories",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1023,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "350.00",
    color: "Blank and White",
    badge: true,
    category: "Home & Garden",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1024,
    img: spfOne,
    productName: "Cap for Boys",
    price: "350.00",
    color: "Blank and White",
    badge: true,
    category: "Accessories",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1025,
    img: spfTwo,
    productName: "Tea Table",
    price: "1800.00",
    color: "Gray",
    badge: true,
    category: "Furniture",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1026,
    img: spfThree,
    productName: "Headphones",
    price: "250.00",
    color: "Mixed",
    badge: true,
    category: "Electronics",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1027,
    img: spfFour,
    productName: "Sun glasses",
    price: "2200.00",
    color: "Black",
    badge: true,
    category: "Accessories",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1028,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "350.00",
    color: "Blank and White",
    badge: true,
    category: "Home & Garden",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1029,
    img: bestSellerTwo,
    productName: "New Backpack",
    price: "1800.00",
    color: "Gray",
    badge: false,
    category: "Bags",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1030,
    img: bestSellerThree,
    productName: "Household materials",
    price: "250.00",
    color: "Mixed",
    badge: true,
    category: "Home & Garden",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1031,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "2200.00",
    color: "Black",
    badge: false,
    category: "Bags",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1032,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "440.00",
    color: "Black",
    badge: true,
    category: "Home & Garden",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1033,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "2500.00",
    color: "Black",
    badge: true,
    category: "Electronics",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1034,
    img: newArrThree,
    productName: "cloth Basket",
    price: "800.00",
    color: "Mixed",
    badge: true,
    category: "Home & Garden",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1035,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "600.00",
    color: "Mixed",
    badge: false,
    category: "Toys & Games",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1036,
    img: newArrTwo,
    productName: "Funny toys for babies",
    price: "600.00",
    color: "Mixed",
    badge: false,
    category: "Toys & Games",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1037,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "600.00",
    color: "Mixed",
    badge: false,
    category: "Toys & Games",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1038,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "2500.00",
    color: "Black",
    badge: true,
    category: "Electronics",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1039,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "2200.00",
    color: "Black",
    badge: false,
    category: "Bags",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1040,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "440.00",
    color: "Black",
    badge: true,
    category: "Home & Garden",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1041,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "2500.00",
    color: "Black",
    badge: true,
    category: "Electronics",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1042,
    img: newArrThree,
    productName: "cloth Basket",
    price: "800.00",
    color: "Mixed",
    badge: true,
    category: "Home & Garden",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1043,
    img: spfThree,
    productName: "Headphones",
    price: "250.00",
    color: "Mixed",
    badge: true,
    category: "Electronics",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1044,
    img: spfFour,
    productName: "Sun glasses",
    price: "2200.00",
    color: "Black",
    badge: true,
    category: "Accessories",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1045,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "350.00",
    color: "Blank and White",
    badge: true,
    category: "Home & Garden",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1046,
    img: spfOne,
    productName: "Cap for Boys",
    price: "350.00",
    color: "Blank and White",
    badge: true,
    category: "Accessories",
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },

  // =================== MOBILE & TABLETS ===================
  {
    _id: 2001,
    img: spfOne,
    productName: "iPhone 15 Pro Max",
    price: "49900.00",
    color: "Natural Titanium",
    badge: true,
    category: "Mobile & Tablets",
    des: "Latest iPhone with advanced camera system and A17 Pro chip.",
  },
  {
    _id: 2002,
    img: spfTwo,
    productName: "Samsung Galaxy S24 Ultra",
    price: "39900.00",
    color: "Titanium Black",
    badge: true,
    category: "Mobile & Tablets",
    des: "Premium Android smartphone with S Pen and 200MP camera.",
  },
  {
    _id: 2003,
    img: spfThree,
    productName: "Google Pixel 8 Pro",
    price: "29900.00",
    color: "Obsidian",
    badge: false,
    category: "Mobile & Tablets",
    des: "Pure Android experience with exceptional camera capabilities.",
  },
  {
    _id: 2004,
    img: spfFour,
    productName: "OnePlus 12",
    price: "24900.00",
    color: "Silky Black",
    badge: true,
    category: "Mobile & Tablets",
    des: "Fast charging flagship with smooth OxygenOS experience.",
  },
  {
    _id: 2005,
    img: bestSellerOne,
    productName: "iPad Pro 12.9-inch",
    price: "34900.00",
    color: "Space Gray",
    badge: true,
    category: "Mobile & Tablets",
    des: "Powerful tablet with M2 chip for professional work.",
  },
  {
    _id: 2006,
    img: bestSellerTwo,
    productName: "Samsung Galaxy Tab S9",
    price: "19900.00",
    color: "Graphite",
    badge: false,
    category: "Mobile & Tablets",
    des: "Premium Android tablet with S Pen included.",
  },
  {
    _id: 2007,
    img: bestSellerThree,
    productName: "Xiaomi 14 Ultra",
    price: "29900.00",
    color: "White",
    badge: true,
    category: "Mobile & Tablets",
    des: "Leica camera partnership with professional photography features.",
  },
  {
    _id: 2008,
    img: bestSellerFour,
    productName: "iPhone 15",
    price: "24900.00",
    color: "Blue",
    badge: false,
    category: "Mobile & Tablets",
    des: "Standard iPhone 15 with Dynamic Island and USB-C.",
  },
  {
    _id: 2009,
    img: newArrOne,
    productName: "Samsung Galaxy Z Fold 5",
    price: "49900.00",
    color: "Phantom Black",
    badge: true,
    category: "Mobile & Tablets",
    des: "Foldable smartphone with large internal screen.",
  },
  {
    _id: 2010,
    img: newArrTwo,
    productName: "iPad Air",
    price: "19900.00",
    color: "Starlight",
    badge: false,
    category: "Mobile & Tablets",
    des: "Lightweight tablet with M1 chip for everyday use.",
  },

  // =================== COMPUTERS & LAPTOPS ===================
  {
    _id: 3001,
    img: spfOne,
    productName: "MacBook Pro 16-inch M3",
    price: "149900.00",
    color: "Space Gray",
    badge: true,
    category: "Computers & Laptops",
    des: "Professional laptop with M3 chip and stunning Liquid Retina XDR display.",
  },
  {
    _id: 3002,
    img: spfTwo,
    productName: "Dell XPS 13",
    price: "79900.00",
    color: "Platinum Silver",
    badge: true,
    category: "Computers & Laptops",
    des: "Ultra-portable laptop with InfinityEdge display.",
  },
  {
    _id: 3003,
    img: spfThree,
    productName: "HP Spectre x360",
    price: "89900.00",
    color: "Nightfall Black",
    badge: false,
    category: "Computers & Laptops",
    des: "2-in-1 convertible laptop with premium build quality.",
  },
  {
    _id: 3004,
    img: spfFour,
    productName: "Lenovo ThinkPad X1 Carbon",
    price: "99900.00",
    color: "Black",
    badge: true,
    category: "Computers & Laptops",
    des: "Business laptop with legendary keyboard and durability.",
  },
  {
    _id: 3005,
    img: bestSellerOne,
    productName: "ASUS ROG Strix G15",
    price: "109900.00",
    color: "Eclipse Gray",
    badge: true,
    category: "Computers & Laptops",
    des: "Gaming laptop with RTX 4070 and AMD Ryzen 9.",
  },
  {
    _id: 3006,
    img: bestSellerTwo,
    productName: "Apple MacBook Air M2",
    price: "69900.00",
    color: "Midnight",
    badge: false,
    category: "Computers & Laptops",
    des: "Ultra-thin laptop with all-day battery life.",
  },
  {
    _id: 3007,
    img: bestSellerThree,
    productName: "Microsoft Surface Laptop 5",
    price: "79900.00",
    color: "Platinum",
    badge: true,
    category: "Computers & Laptops",
    des: "Premium Windows laptop with touchscreen display.",
  },
  {
    _id: 3008,
    img: bestSellerFour,
    productName: "Razer Blade 15",
    price: "149900.00",
    color: "Mercury White",
    badge: true,
    category: "Computers & Laptops",
    des: "High-end gaming laptop with RTX 4080.",
  },

  // =================== MEN'S CLOTHING ===================
  {
    _id: 4001,
    img: spfOne,
    productName: "Nike Air Max 270",
    price: "1500.00",
    color: "Black",
    badge: true,
    category: "Men's Clothing",
    des: "Comfortable running shoes with Air Max cushioning.",
  },
  {
    _id: 4002,
    img: spfTwo,
    productName: "Levi's 501 Original Jeans",
    price: "890.00",
    color: "Dark Wash",
    badge: false,
    category: "Men's Clothing",
    des: "Classic straight fit jeans that never go out of style.",
  },
  {
    _id: 4003,
    img: spfThree,
    productName: "Adidas Ultraboost 22",
    price: "1800.00",
    color: "Core Black",
    badge: true,
    category: "Men's Clothing",
    des: "Running shoes with Boost technology for energy return.",
  },
  {
    _id: 4004,
    img: spfFour,
    productName: "H&M Slim Fit Shirt",
    price: "299.00",
    color: "White",
    badge: false,
    category: "Men's Clothing",
    des: "Cotton shirt perfect for casual and formal occasions.",
  },
  {
    _id: 4005,
    img: bestSellerOne,
    productName: "Puma Suede Classic",
    price: "750.00",
    color: "Black",
    badge: true,
    category: "Men's Clothing",
    des: "Iconic sneakers with suede upper and rubber outsole.",
  },
  {
    _id: 4006,
    img: bestSellerTwo,
    productName: "Zara Wool Blazer",
    price: "1990.00",
    color: "Navy",
    badge: true,
    category: "Men's Clothing",
    des: "Tailored blazer made from premium wool blend.",
  },
  {
    _id: 4007,
    img: bestSellerThree,
    productName: "Under Armour Tech T-Shirt",
    price: "350.00",
    color: "Gray",
    badge: false,
    category: "Men's Clothing",
    des: "Moisture-wicking t-shirt for active lifestyle.",
  },
  {
    _id: 4008,
    img: bestSellerFour,
    productName: "Tommy Hilfiger Polo Shirt",
    price: "650.00",
    color: "Red",
    badge: true,
    category: "Men's Clothing",
    des: "Classic polo shirt with signature logo embroidery.",
  },

  // =================== WOMEN'S CLOTHING ===================
  {
    _id: 5001,
    img: spfOne,
    productName: "Nike Air Force 1",
    price: "1100.00",
    color: "White",
    badge: true,
    category: "Women's Clothing",
    des: "Legendary basketball shoes that transcend generations.",
  },
  {
    _id: 5002,
    img: spfTwo,
    productName: "H&M Midi Dress",
    price: "499.00",
    color: "Floral Print",
    badge: false,
    category: "Women's Clothing",
    des: "Flowy midi dress perfect for summer occasions.",
  },
  {
    _id: 5003,
    img: spfThree,
    productName: "Adidas Stan Smith",
    price: "850.00",
    color: "White",
    badge: true,
    category: "Women's Clothing",
    des: "Clean and minimalist tennis shoes.",
  },
  {
    _id: 5004,
    img: spfFour,
    productName: "Zara Leather Jacket",
    price: "2990.00",
    color: "Black",
    badge: true,
    category: "Women's Clothing",
    des: "Timeless leather jacket with modern fit.",
  },
  {
    _id: 5005,
    img: bestSellerOne,
    productName: "Converse Chuck Taylor",
    price: "650.00",
    color: "Navy",
    badge: false,
    category: "Women's Clothing",
    des: "Classic high-top sneakers with canvas upper.",
  },
  {
    _id: 5006,
    img: bestSellerTwo,
    productName: "Mango Blouse",
    price: "399.00",
    color: "Coral",
    badge: true,
    category: "Women's Clothing",
    des: "Silk blouse with elegant neckline detail.",
  },
  {
    _id: 5007,
    img: bestSellerThree,
    productName: "Victoria's Secret Bra",
    price: "450.00",
    color: "Black Lace",
    badge: false,
    category: "Women's Clothing",
    des: "Comfortable and supportive everyday bra.",
  },
  {
    _id: 5008,
    img: bestSellerFour,
    productName: "Gucci Handbag",
    price: "18900.00",
    color: "Beige",
    badge: true,
    category: "Women's Clothing",
    des: "Luxury leather handbag with GG Supreme canvas.",
  },

  // =================== SHOES ===================
  {
    _id: 6001,
    img: spfOne,
    productName: "Jordan 1 Retro High",
    price: "1700.00",
    color: "Chicago",
    badge: true,
    category: "Shoes",
    des: "Iconic basketball shoes with legendary status.",
  },
  {
    _id: 6002,
    img: spfTwo,
    productName: "New Balance 574",
    price: "850.00",
    color: "Navy",
    badge: false,
    category: "Shoes",
    des: "Classic running shoes with vintage style.",
  },
  {
    _id: 6003,
    img: spfThree,
    productName: "Vans Old Skool",
    price: "650.00",
    color: "Black",
    badge: true,
    category: "Shoes",
    des: "Skate shoes with sidestripe and durable canvas upper.",
  },
  {
    _id: 6004,
    img: spfFour,
    productName: "Timberland 6-Inch Boot",
    price: "1980.00",
    color: "Wheat",
    badge: true,
    category: "Shoes",
    des: "Waterproof leather boots for rugged outdoor use.",
  },
  {
    _id: 6005,
    img: bestSellerOne,
    productName: "Crocs Classic Clog",
    price: "399.00",
    color: "Navy",
    badge: false,
    category: "Shoes",
    des: "Comfortable foam clogs with iconic design.",
  },
  {
    _id: 6006,
    img: bestSellerTwo,
    productName: "Dr. Martens 1460",
    price: "1500.00",
    color: "Black",
    badge: true,
    category: "Shoes",
    des: "Heavy-duty leather boots with yellow stitching.",
  },
  {
    _id: 6007,
    img: bestSellerThree,
    productName: "Birkenstock Arizona",
    price: "1100.00",
    color: "Brown",
    badge: false,
    category: "Shoes",
    des: "Contoured footbed sandals with adjustable straps.",
  },
  {
    _id: 6008,
    img: bestSellerFour,
    productName: "UGG Classic Short",
    price: "1600.00",
    color: "Chestnut",
    badge: true,
    category: "Shoes",
    des: "Sheepskin boots with UGGpure wool lining.",
  },

  // =================== BOOKS ===================
  {
    _id: 7001,
    img: spfOne,
    productName: "Atomic Habits",
    price: "169.00",
    color: "Paperback",
    badge: true,
    category: "Books",
    des: "Transform your life with tiny changes in behavior.",
  },
  {
    _id: 7002,
    img: spfTwo,
    productName: "The Psychology of Money",
    price: "149.00",
    color: "Hardcover",
    badge: false,
    category: "Books",
    des: "Timeless lessons on wealth, greed, and happiness.",
  },
  {
    _id: 7003,
    img: spfThree,
    productName: "Sapiens: A Brief History",
    price: "189.00",
    color: "Paperback",
    badge: true,
    category: "Books",
    des: "The fascinating story of how Homo sapiens conquered Earth.",
  },
  {
    _id: 7004,
    img: spfFour,
    productName: "Dune",
    price: "129.00",
    color: "Paperback",
    badge: false,
    category: "Books",
    des: "Epic science fiction masterpiece by Frank Herbert.",
  },
  {
    _id: 7005,
    img: bestSellerOne,
    productName: "The Midnight Library",
    price: "159.00",
    color: "Hardcover",
    badge: true,
    category: "Books",
    des: "Between life and death there is a library.",
  },
  {
    _id: 7006,
    img: bestSellerTwo,
    productName: "Educated",
    price: "139.00",
    color: "Paperback",
    badge: false,
    category: "Books",
    des: "A memoir about education and survival.",
  },
  {
    _id: 7007,
    img: bestSellerThree,
    productName: "The Seven Husbands of Evelyn Hugo",
    price: "149.00",
    color: "Paperback",
    badge: true,
    category: "Books",
    des: "A reclusive Hollywood icon finally tells her story.",
  },
  {
    _id: 7008,
    img: bestSellerFour,
    productName: "Where the Crawdads Sing",
    price: "169.00",
    color: "Hardcover",
    badge: true,
    category: "Books",
    des: "A mystery wrapped in a coming-of-age story.",
  },

  // =================== SPORTS & OUTDOORS ===================
  {
    _id: 8001,
    img: spfOne,
    productName: "Nike Air Zoom Pegasus",
    price: "1200.00",
    color: "Black/White",
    badge: true,
    category: "Sports & Outdoors",
    des: "Versatile running shoes for training and racing.",
  },
  {
    _id: 8002,
    img: spfTwo,
    productName: "Peloton Bike",
    price: "249500.00",
    color: "Black",
    badge: true,
    category: "Sports & Outdoors",
    des: "Interactive exercise bike with live and on-demand classes.",
  },
  {
    _id: 8003,
    img: spfThree,
    productName: "Yeti Cooler",
    price: "2999.00",
    color: "White",
    badge: false,
    category: "Sports & Outdoors",
    des: "Insulated cooler that keeps ice for days.",
  },
  {
    _id: 8004,
    img: spfFour,
    productName: "Garmin Forerunner 265",
    price: "4499.00",
    color: "Black",
    badge: true,
    category: "Sports & Outdoors",
    des: "Advanced GPS running watch with health monitoring.",
  },
  {
    _id: 8005,
    img: bestSellerOne,
    productName: "Wilson NFL Football",
    price: "299.00",
    color: "Brown",
    badge: false,
    category: "Sports & Outdoors",
    des: "Official NFL game football with composite leather.",
  },
  {
    _id: 8006,
    img: bestSellerTwo,
    productName: "Coleman Lantern",
    price: "499.00",
    color: "Green",
    badge: true,
    category: "Sports & Outdoors",
    des: "LED lantern for camping and outdoor activities.",
  },
  {
    _id: 8007,
    img: bestSellerThree,
    productName: "Patagonia Jacket",
    price: "1990.00",
    color: "Black",
    badge: true,
    category: "Sports & Outdoors",
    des: "Waterproof jacket made from recycled materials.",
  },
  {
    _id: 8008,
    img: bestSellerFour,
    productName: "Titleist Golf Balls",
    price: "449.00",
    color: "Yellow",
    badge: false,
    category: "Sports & Outdoors",
    des: "Premium golf balls for improved distance and control.",
  },

  // =================== BEAUTY & PERSONAL CARE ===================
  {
    _id: 9001,
    img: spfOne,
    productName: "The Ordinary Hyaluronic Acid",
    price: "69.00",
    color: "Clear",
    badge: true,
    category: "Beauty & Personal Care",
    des: "Hydrating serum with multiple molecular weights of HA.",
  },
  {
    _id: 9002,
    img: spfTwo,
    productName: "CeraVe Moisturizing Cream",
    price: "169.00",
    color: "White",
    badge: false,
    category: "Beauty & Personal Care",
    des: "Fragrance-free moisturizer for sensitive skin.",
  },
  {
    _id: 9003,
    img: spfThree,
    productName: "Fenty Beauty Pro Filt'r Soft Matte",
    price: "350.00",
    color: "Shade 300",
    badge: true,
    category: "Beauty & Personal Care",
    des: "Long-wear foundation with 50 shades for all skin tones.",
  },
  {
    _id: 9004,
    img: spfFour,
    productName: "Dyson Airwrap",
    price: "5999.00",
    color: "Nickel/Copper",
    badge: true,
    category: "Beauty & Personal Care",
    des: "Multi-styling tool for curls, waves, and smoothing.",
  },
  {
    _id: 9005,
    img: bestSellerOne,
    productName: "Drunk Elephant C-Firma",
    price: "1690.00",
    color: "Cream",
    badge: true,
    category: "Beauty & Personal Care",
    des: "Vitamin C serum for brightening and firming.",
  },
  {
    _id: 9006,
    img: bestSellerTwo,
    productName: "Bioderma Sebium Mat Control",
    price: "199.00",
    color: "Clear",
    badge: false,
    category: "Beauty & Personal Care",
    des: "Mattifying cream for oily and acne-prone skin.",
  },
  {
    _id: 9007,
    img: bestSellerThree,
    productName: "Oribe Shampoo",
    price: "680.00",
    color: "Gold",
    badge: true,
    category: "Beauty & Personal Care",
    des: "Luxury shampoo for damaged and color-treated hair.",
  },
  {
    _id: 9008,
    img: bestSellerFour,
    productName: "Glossier Boy Brow",
    price: "160.00",
    color: "Brown",
    badge: false,
    category: "Beauty & Personal Care",
    des: "Brow gel that tames, shapes, and sets eyebrows.",
  },

  // =================== HEALTH & HOUSEHOLD ===================
  {
    _id: 10001,
    img: spfOne,
    productName: "Vitamix Blender",
    price: "6999.00",
    color: "Black",
    badge: true,
    category: "Health & Household",
    des: "Professional-grade blender for smoothies and soups.",
  },
  {
    _id: 10002,
    img: spfTwo,
    productName: "Dyson Vacuum",
    price: "5999.00",
    color: "Nickel",
    badge: true,
    category: "Health & Household",
    des: "Cordless vacuum with powerful suction and HEPA filter.",
  },
  {
    _id: 10003,
    img: spfThree,
    productName: "Instant Pot Duo",
    price: "899.00",
    color: "Stainless Steel",
    badge: false,
    category: "Health & Household",
    des: "7-in-1 electric pressure cooker for fast cooking.",
  },
  {
    _id: 10004,
    img: spfFour,
    productName: "Ninja Air Fryer",
    price: "1299.00",
    color: "Black",
    badge: true,
    category: "Health & Household",
    des: "Large capacity air fryer for healthy frying.",
  },
  {
    _id: 10005,
    img: bestSellerOne,
    productName: "Roomba Robot Vacuum",
    price: "2999.00",
    color: "Black",
    badge: true,
    category: "Health & Household",
    des: "Smart robot vacuum that cleans automatically.",
  },
  {
    _id: 10006,
    img: bestSellerTwo,
    productName: "Breville Espresso Machine",
    price: "6999.00",
    color: "Stainless Steel",
    badge: true,
    category: "Health & Household",
    des: "Professional espresso machine for home use.",
  },
  {
    _id: 10007,
    img: bestSellerThree,
    productName: "KitchenAid Stand Mixer",
    price: "3799.00",
    color: "Empire Red",
    badge: false,
    category: "Health & Household",
    des: "5-quart tilt-head stand mixer with multiple attachments.",
  },
  {
    _id: 10008,
    img: bestSellerFour,
    productName: "Nespresso Coffee Machine",
    price: "1999.00",
    color: "Black",
    badge: true,
    category: "Health & Household",
    des: "Capsule coffee machine for quick brewing.",
  },

  // =================== AUTOMOTIVE ===================
  {
    _id: 11001,
    img: spfOne,
    productName: "Michelin Pilot Sport 4S",
    price: "1899.00",
    color: "Black",
    badge: true,
    category: "Automotive",
    des: "Ultra-high performance tires for sports cars.",
  },
  {
    _id: 11002,
    img: spfTwo,
    productName: "Garmin GPS Navigator",
    price: "3999.00",
    color: "Black",
    badge: false,
    category: "Automotive",
    des: "GPS device with real-time traffic and voice guidance.",
  },
  {
    _id: 11003,
    img: spfThree,
    productName: "Chemical Guys Car Wax",
    price: "299.00",
    color: "Clear",
    badge: true,
    category: "Automotive",
    des: "Professional car wax for protection and shine.",
  },
  {
    _id: 11004,
    img: spfFour,
    productName: "Meguiar's Car Wash Soap",
    price: "199.00",
    color: "Blue",
    badge: false,
    category: "Automotive",
    des: "pH-balanced car wash soap that won't strip wax.",
  },
  {
    _id: 11005,
    img: bestSellerOne,
    productName: "Armor All Tire Shine",
    price: "99.00",
    color: "Black",
    badge: true,
    category: "Automotive",
    des: "Tire dressing that provides long-lasting shine.",
  },
  {
    _id: 11006,
    img: bestSellerTwo,
    productName: "Rain-X Windshield Treatment",
    price: "149.00",
    color: "Clear",
    badge: false,
    category: "Automotive",
    des: "Water repellent treatment for better visibility in rain.",
  },
  {
    _id: 11007,
    img: bestSellerThree,
    productName: "Mobil 1 Synthetic Oil",
    price: "399.00",
    color: "Amber",
    badge: true,
    category: "Automotive",
    des: "High-performance synthetic motor oil.",
  },
  {
    _id: 11008,
    img: bestSellerFour,
    productName: "Bosch Spark Plugs",
    price: "249.00",
    color: "Copper",
    badge: false,
    category: "Automotive",
    des: "Premium spark plugs for improved engine performance.",
  },

  // =================== JEWELRY & WATCHES ===================
  {
    _id: 12001,
    img: spfOne,
    productName: "Rolex Submariner",
    price: "899900.00",
    color: "Black Dial",
    badge: true,
    category: "Jewelry & Watches",
    des: "Iconic diver's watch with Oystersteel case.",
  },
  {
    _id: 12002,
    img: spfTwo,
    productName: "Cartier Love Bracelet",
    price: "650.00",
    color: "Yellow Gold",
    badge: true,
    category: "Jewelry & Watches",
    des: "Heart-shaped bracelet that symbolizes eternal love.",
  },
  {
    _id: 12003,
    img: spfThree,
    productName: "Tiffany & Co Elsa Peretti",
    price: "450.00",
    color: "Silver",
    badge: false,
    category: "Jewelry & Watches",
    des: "Open heart pendant necklace in sterling silver.",
  },
  {
    _id: 12004,
    img: spfFour,
    productName: "Omega Speedmaster",
    price: "599.00",
    color: "Black",
    badge: true,
    category: "Jewelry & Watches",
    des: "The Moonwatch - first watch worn on the moon.",
  },
  {
    _id: 12005,
    img: bestSellerOne,
    productName: "Pandora Charm Bracelet",
    price: "129.00",
    color: "Silver",
    badge: false,
    category: "Jewelry & Watches",
    des: "Sterling silver bracelet with interchangeable charms.",
  },
  {
    _id: 12006,
    img: bestSellerTwo,
    productName: "Swarovski Crystal Earrings",
    price: "890.00",
    color: "Clear",
    badge: true,
    category: "Jewelry & Watches",
    des: "Elegant crystal stud earrings with secure posts.",
  },
  {
    _id: 12007,
    img: bestSellerThree,
    productName: "Seiko Presage",
    price: "2990.00",
    color: "Blue Dial",
    badge: false,
    category: "Jewelry & Watches",
    des: "Japanese automatic watch with enamel dial.",
  },
  {
    _id: 12008,
    img: bestSellerFour,
    productName: "Kate Spade Ring",
    price: "450.00",
    color: "Gold",
    badge: true,
    category: "Jewelry & Watches",
    des: "Delicate bow ring with pavé crystal accents.",
  },

  // =================== MUSICAL INSTRUMENTS ===================
  {
    _id: 13001,
    img: spfOne,
    productName: "Fender American Ultra II",
    price: "16999.00",
    color: "Sunburst",
    badge: true,
    category: "Musical Instruments",
    des: "Professional electric guitar with Ultra Noiseless pickups.",
  },
  {
    _id: 13002,
    img: spfTwo,
    productName: "Yamaha P-125 Digital Piano",
    price: "6999.00",
    color: "Black",
    badge: false,
    category: "Musical Instruments",
    des: "Portable digital piano with Graded Hammer Standard action.",
  },
  {
    _id: 13003,
    img: spfThree,
    productName: "Pearl Export Series Drum Kit",
    price: "8999.00",
    color: "Wine Red",
    badge: true,
    category: "Musical Instruments",
    des: "5-piece drum kit with hardware and cymbals.",
  },
  {
    _id: 13004,
    img: spfFour,
    productName: "Shure SM7B Microphone",
    price: "3990.00",
    color: "Black",
    badge: true,
    category: "Musical Instruments",
    des: "Professional dynamic microphone for broadcasting.",
  },
  {
    _id: 13005,
    img: bestSellerOne,
    productName: "Taylor 114ce Acoustic Guitar",
    price: "8990.00",
    color: "Natural",
    badge: false,
    category: "Musical Instruments",
    des: "Grand Auditorium acoustic guitar with electronics.",
  },
  {
    _id: 13006,
    img: bestSellerTwo,
    productName: "Roland TD-17KVX V-Drums",
    price: "24999.00",
    color: "Black",
    badge: true,
    category: "Musical Instruments",
    des: "Electronic drum kit with advanced sound engine.",
  },
  {
    _id: 13007,
    img: bestSellerThree,
    productName: "AKG K240 Studio Headphones",
    price: "790.00",
    color: "Black",
    badge: false,
    category: "Musical Instruments",
    des: "Professional semi-open studio headphones.",
  },
  {
    _id: 13008,
    img: bestSellerFour,
    productName: "Casio CT-S300 Keyboard",
    price: "2999.00",
    color: "Black",
    badge: true,
    category: "Musical Instruments",
    des: "61-key portable keyboard with 400 tones.",
  },

  // =================== PET SUPPLIES ===================
  {
    _id: 14001,
    img: spfOne,
    productName: "Blue Buffalo Dog Food",
    price: "499.00",
    color: "Chicken",
    badge: true,
    category: "Pet Supplies",
    des: "Natural dog food with real chicken as the first ingredient.",
  },
  {
    _id: 14002,
    img: spfTwo,
    productName: "Furbo Dog Camera",
    price: "2499.00",
    color: "White",
    badge: true,
    category: "Pet Supplies",
    des: "WiFi pet camera with two-way audio and treat tossing.",
  },
  {
    _id: 14003,
    img: spfThree,
    productName: "Kong Classic Dog Toy",
    price: "129.00",
    color: "Red",
    badge: false,
    category: "Pet Supplies",
    des: "Durable rubber toy for chewing and fetching.",
  },
  {
    _id: 14004,
    img: spfFour,
    productName: "Purina Cat Chow",
    price: "199.00",
    color: "Salmon",
    badge: true,
    category: "Pet Supplies",
    des: "Complete nutrition for adult cats.",
  },
  {
    _id: 14005,
    img: bestSellerOne,
    productName: "PetSafe Automatic Feeder",
    price: "599.00",
    color: "White",
    badge: false,
    category: "Pet Supplies",
    des: "Programmable automatic pet feeder for multiple meals.",
  },
  {
    _id: 14006,
    img: bestSellerTwo,
    productName: "Midwest Feline Cat Tree",
    price: "899.00",
    color: "Beige",
    badge: true,
    category: "Pet Supplies",
    des: "Multi-level cat tree with scratching posts and beds.",
  },
  {
    _id: 14007,
    img: bestSellerThree,
    productName: "Arm & Hammer Cat Litter",
    price: "249.00",
    color: "Multi-Cat",
    badge: false,
    category: "Pet Supplies",
    des: "Clumping cat litter with odor control.",
  },
  {
    _id: 14008,
    img: bestSellerFour,
    productName: "Chuckit! Paraflight Disc",
    price: "149.00",
    color: "Orange",
    badge: true,
    category: "Pet Supplies",
    des: "Soft flying disc for dogs that floats on water.",
  },

  // =================== OFFICE PRODUCTS ===================
  {
    _id: 15001,
    img: spfOne,
    productName: "Dyson Purifier Humidify+Cool",
    price: "6999.00",
    color: "White",
    badge: true,
    category: "Office Products",
    des: "Air purifier, humidifier, and fan in one device.",
  },
  {
    _id: 15002,
    img: spfTwo,
    productName: "Herman Miller Aeron Chair",
    price: "129900.00",
    color: "Carbon",
    badge: true,
    category: "Office Products",
    des: "Ergonomic office chair designed for all-day comfort.",
  },
  {
    _id: 15003,
    img: spfThree,
    productName: "LG 27-inch 4K Monitor",
    price: "3499.00",
    color: "Black",
    badge: false,
    category: "Office Products",
    des: "4K UHD monitor with IPS panel and HDR support.",
  },
  {
    _id: 15004,
    img: spfFour,
    productName: "Logitech MX Master 3S",
    price: "999.00",
    color: "Graphite",
    badge: true,
    category: "Office Products",
    des: "Advanced wireless mouse with customizable buttons.",
  },
  {
    _id: 15005,
    img: bestSellerOne,
    productName: "Anker PowerCore 20K",
    price: "499.00",
    color: "Black",
    badge: false,
    category: "Office Products",
    des: "Portable power bank with 20,000mAh capacity.",
  },
  {
    _id: 15006,
    img: bestSellerTwo,
    productName: "Brother Laser Printer",
    price: "1999.00",
    color: "Black",
    badge: true,
    category: "Office Products",
    des: "Monochrome laser printer for home office use.",
  },
  {
    _id: 15007,
    img: bestSellerThree,
    productName: "Rocketbook Smart Notebook",
    price: "349.00",
    color: "Black",
    badge: false,
    category: "Office Products",
    des: "Reusable smart notebook that digitizes your notes.",
  },
  {
    _id: 15008,
    img: bestSellerFour,
    productName: "Tile Mate Bluetooth Tracker",
    price: "249.00",
    color: "White",
    badge: true,
    category: "Office Products",
    des: "Bluetooth tracker to find keys, bags, and more.",
  },

  // =================== INDUSTRIAL & SCIENTIFIC ===================
  {
    _id: 16001,
    img: spfOne,
    productName: "Fluke 87V Digital Multimeter",
    price: "4999.00",
    color: "Red/Gray",
    badge: true,
    category: "Industrial & Scientific",
    des: "True RMS digital multimeter for professional use.",
  },
  {
    _id: 16002,
    img: spfTwo,
    productName: "3M Safety Glasses",
    price: "99.00",
    color: "Clear",
    badge: false,
    category: "Industrial & Scientific",
    des: "ANSI Z87.1 certified safety glasses with anti-fog coating.",
  },
  {
    _id: 16003,
    img: spfThree,
    productName: "Klein Tools Lineman Pliers",
    price: "399.00",
    color: "Black",
    badge: true,
    category: "Industrial & Scientific",
    des: "Heavy-duty pliers for cutting and bending wire.",
  },
  {
    _id: 16004,
    img: spfFour,
    productName: "Milwaukee M18 Cordless Drill",
    price: "1490.00",
    color: "Red",
    badge: true,
    category: "Industrial & Scientific",
    des: "18V cordless drill with brushless motor.",
  },
  {
    _id: 16005,
    img: bestSellerOne,
    productName: "DeWalt Circular Saw",
    price: "1990.00",
    color: "Yellow/Black",
    badge: false,
    category: "Industrial & Scientific",
    des: "7-1/4 inch circular saw with electric brake.",
  },
  {
    _id: 16006,
    img: bestSellerTwo,
    productName: "Bosch Laser Measure",
    price: "799.00",
    color: "Green",
    badge: true,
    category: "Industrial & Scientific",
    des: "Laser distance measurer with Bluetooth connectivity.",
  },
  {
    _id: 16007,
    img: bestSellerThree,
    productName: "Irwin Vise-Grip Pliers",
    price: "149.00",
    color: "Blue",
    badge: false,
    category: "Industrial & Scientific",
    des: "Locking pliers with adjustable jaw capacity.",
  },
  {
    _id: 16008,
    img: bestSellerFour,
    productName: "Stanley Tape Measure",
    price: "129.00",
    color: "Yellow",
    badge: true,
    category: "Industrial & Scientific",
    des: "25-foot tape measure with blade armor coating.",
  },

  // =================== MORE MOBILE & TABLETS ===================
  {
    _id: 2011,
    img: spfOne,
    productName: "Samsung Galaxy A54",
    price: "3490.00",
    color: "Awesome Violet",
    badge: false,
    category: "Mobile & Tablets",
    des: "Mid-range smartphone with 120Hz display and long battery life.",
  },
  {
    _id: 2012,
    img: spfTwo,
    productName: "Motorola Edge 40 Pro",
    price: "6990.00",
    color: "Viva Magenta",
    badge: true,
    category: "Mobile & Tablets",
    des: "Premium Android phone with curved display and fast charging.",
  },
  {
    _id: 2013,
    img: spfThree,
    productName: "Nokia X30",
    price: "4990.00",
    color: "Cloudy Blue",
    badge: false,
    category: "Mobile & Tablets",
    des: "Durable phone with 5 years of updates and clean Android.",
  },
  {
    _id: 2014,
    img: spfFour,
    productName: "Sony Xperia 1 V",
    price: "12990.00",
    color: "Black",
    badge: true,
    category: "Mobile & Tablets",
    des: "Professional camera phone with 4K 120fps video recording.",
  },
  {
    _id: 2015,
    img: bestSellerOne,
    productName: "Asus Zenfone 10",
    price: "7990.00",
    color: "Midnight Black",
    badge: true,
    category: "Mobile & Tablets",
    des: "Compact flagship with Snapdragon 8 Gen 2.",
  },
  {
    _id: 2016,
    img: bestSellerTwo,
    productName: "iPad Pro 11-inch",
    price: "7990.00",
    color: "Silver",
    badge: false,
    category: "Mobile & Tablets",
    des: "Powerful tablet with M2 chip for creative professionals.",
  },
  {
    _id: 2017,
    img: bestSellerThree,
    productName: "Samsung Galaxy Tab S9+",
    price: "8990.00",
    color: "Beige",
    badge: true,
    category: "Mobile & Tablets",
    des: "Large screen tablet with S Pen and DeX mode.",
  },
  {
    _id: 2018,
    img: bestSellerFour,
    productName: "Lenovo Tab P12 Pro",
    price: "4990.00",
    color: "Storm Gray",
    badge: false,
    category: "Mobile & Tablets",
    des: "Android tablet with OLED display and precision pen.",
  },

  // =================== MORE COMPUTERS & LAPTOPS ===================
  {
    _id: 3009,
    img: spfOne,
    productName: "Acer Predator Helios 16",
    price: "199900.00",
    color: "Abyssal Black",
    badge: true,
    category: "Computers & Laptops",
    des: "Gaming laptop with RTX 4070 and 165Hz display.",
  },
  {
    _id: 3010,
    img: spfTwo,
    productName: "Framework Laptop 13",
    price: "8990.00",
    color: "Silver",
    badge: true,
    category: "Computers & Laptops",
    des: "Modular and repairable laptop built for the future.",
  },
  {
    _id: 3011,
    img: spfThree,
    productName: "MSI Creator Z16",
    price: "249900.00",
    color: "Cosmic Silver",
    badge: true,
    category: "Computers & Laptops",
    des: "Content creation laptop with RTX 4060 and Mini LED display.",
  },
  {
    _id: 3012,
    img: spfFour,
    productName: "HP Envy 17",
    price: "149900.00",
    color: "Natural Silver",
    badge: false,
    category: "Computers & Laptops",
    des: "Large screen laptop with AMD Ryzen and Radeon graphics.",
  },
  {
    _id: 3013,
    img: bestSellerOne,
    productName: "Apple Mac Studio",
    price: "199900.00",
    color: "Silver",
    badge: true,
    category: "Computers & Laptops",
    des: "Compact desktop computer with M2 Ultra chip.",
  },
  {
    _id: 3014,
    img: bestSellerTwo,
    productName: "Dell Alienware Aurora R15",
    price: "199900.00",
    color: "Dark Side of the Moon",
    badge: true,
    category: "Computers & Laptops",
    des: "Gaming desktop with RTX 4070 Ti and Intel Core i7.",
  },
  {
    _id: 3015,
    img: bestSellerThree,
    productName: "Lenovo Legion Tower 7",
    price: "229900.00",
    color: "Phantom Blue",
    badge: true,
    category: "Computers & Laptops",
    des: "High-end gaming desktop with liquid cooling.",
  },
  {
    _id: 3016,
    img: bestSellerFour,
    productName: "Apple iMac 24-inch",
    price: "129900.00",
    color: "Blue",
    badge: false,
    category: "Computers & Laptops",
    des: "All-in-one computer with M3 chip and vibrant display.",
  },

  // =================== MORE MEN'S CLOTHING ===================
  {
    _id: 4009,
    img: spfOne,
    productName: "Ralph Lauren Polo Shirt",
    price: "890.00",
    color: "Navy",
    badge: true,
    category: "Men's Clothing",
    des: "Classic polo shirt with embroidered pony logo.",
  },
  {
    _id: 4010,
    img: spfTwo,
    productName: "Calvin Klein Boxer Briefs",
    price: "240.00",
    color: "Black",
    badge: false,
    category: "Men's Clothing",
    des: "Comfortable cotton boxer briefs with logo waistband.",
  },
  {
    _id: 4011,
    img: spfThree,
    productName: "Hugo Boss Suit",
    price: "5990.00",
    color: "Charcoal",
    badge: true,
    category: "Men's Clothing",
    des: "Tailored wool suit with modern fit.",
  },
  {
    _id: 4012,
    img: spfFour,
    productName: "Nike Dri-FIT T-Shirt",
    price: "250.00",
    color: "White",
    badge: false,
    category: "Men's Clothing",
    des: "Moisture-wicking t-shirt for workouts.",
  },
  {
    _id: 4013,
    img: bestSellerOne,
    productName: "Timberland Boots",
    price: "1980.00",
    color: "Brown",
    badge: true,
    category: "Men's Clothing",
    des: "Waterproof leather boots with rugged design.",
  },
  {
    _id: 4014,
    img: bestSellerTwo,
    productName: "Ray-Ban Aviator Sunglasses",
    price: "1490.00",
    color: "Gold",
    badge: true,
    category: "Sunglasses",
    des: "Classic aviator sunglasses with polarized lenses.",
  },
  {
    _id: 4101,
    img: spfOne,
    productName: "Oak Wood Coffee Table",
    price: "2490.00",
    color: "Natural Oak",
    badge: true,
    category: "Tables",
    des: "Solid oak coffee table with a modern farmhouse design.",
  },
  {
    _id: 4102,
    img: spfTwo,
    productName: "Glass Dining Table",
    price: "3990.00",
    color: "Clear/Black",
    badge: true,
    category: "Tables",
    des: "Contemporary dining table with tempered glass top.",
  },
  {
    _id: 4103,
    img: spfThree,
    productName: "Leather Tote Bag",
    price: "1290.00",
    color: "Tan",
    badge: true,
    category: "Bags",
    des: "Premium leather tote bag with spacious interior.",
  },
  {
    _id: 4104,
    img: spfFour,
    productName: "Modern Accent Chair",
    price: "2190.00",
    color: "Gray",
    badge: false,
    category: "Furniture",
    des: "Comfortable upholstered accent chair with wooden legs.",
  },
  {
    _id: 4015,
    img: bestSellerThree,
    productName: "Levi's 511 Slim Jeans",
    price: "690.00",
    color: "Dark Indigo",
    badge: false,
    category: "Men's Clothing",
    des: "Slim fit jeans with stretch comfort.",
  },
  {
    _id: 4016,
    img: bestSellerFour,
    productName: "Adidas Originals Track Jacket",
    price: "750.00",
    color: "Black",
    badge: true,
    category: "Men's Clothing",
    des: "Classic track jacket with three stripes.",
  },

  // =================== MORE WOMEN'S CLOTHING ===================
  {
    _id: 5009,
    img: spfOne,
    productName: "Zara Midi Skirt",
    price: "499.00",
    color: "Black",
    badge: false,
    category: "Women's Clothing",
    des: "Elegant midi skirt with pleated design.",
  },
  {
    _id: 5010,
    img: spfTwo,
    productName: "H&M Wide Leg Pants",
    price: "399.00",
    color: "Beige",
    badge: true,
    category: "Women's Clothing",
    des: "Comfortable wide leg pants for casual wear.",
  },
  {
    _id: 5011,
    img: spfThree,
    productName: "Victoria's Secret Padded Bra",
    price: "550.00",
    color: "Nude",
    badge: false,
    category: "Women's Clothing",
    des: "Supportive bra with light padding and lace details.",
  },
  {
    _id: 5012,
    img: spfFour,
    productName: "Mango Cardigan",
    price: "599.00",
    color: "Cream",
    badge: true,
    category: "Women's Clothing",
    des: "Soft knit cardigan with button closure.",
  },
  {
    _id: 5013,
    img: bestSellerOne,
    productName: "Nike Sportswear Hoodie",
    price: "850.00",
    color: "Gray",
    badge: true,
    category: "Women's Clothing",
    des: "Comfortable hoodie with kangaroo pocket.",
  },
  {
    _id: 5014,
    img: bestSellerTwo,
    productName: "Forever 21 Crop Top",
    price: "199.00",
    color: "White",
    badge: false,
    category: "Women's Clothing",
    des: "Basic crop top for layering or casual wear.",
  },
  {
    _id: 5015,
    img: bestSellerThree,
    productName: "Uniqlo HeatTech Leggings",
    price: "399.00",
    color: "Black",
    badge: true,
    category: "Women's Clothing",
    des: "Thermal leggings with moisture-wicking technology.",
  },
  {
    _id: 5016,
    img: bestSellerFour,
    productName: "ASOS DESIGN Mini Dress",
    price: "450.00",
    color: "Red",
    badge: false,
    category: "Women's Clothing",
    des: "Flirty mini dress with fitted bodice.",
  },

  // =================== MORE SHOES ===================
  {
    _id: 6009,
    img: spfOne,
    productName: "Reebok Classic Leather",
    price: "750.00",
    color: "White",
    badge: false,
    category: "Shoes",
    des: "Timeless sneakers with soft leather upper.",
  },
  {
    _id: 6010,
    img: spfTwo,
    productName: "Skechers Go Walk",
    price: "650.00",
    color: "Black",
    badge: true,
    category: "Shoes",
    des: "Comfort walking shoes with air-cooled memory foam.",
  },
  {
    _id: 6011,
    img: spfThree,
    productName: "Puma RS-X",
    price: "1100.00",
    color: "White/Puma Black",
    badge: true,
    category: "Shoes",
    des: "Retro running shoes with bold design.",
  },
  {
    _id: 6012,
    img: spfFour,
    productName: "Clarks Desert Boot",
    price: "890.00",
    color: "Tan",
    badge: false,
    category: "Shoes",
    des: "Classic suede desert boots with crepe sole.",
  },
  {
    _id: 6013,
    img: bestSellerOne,
    productName: "Steve Madden Heels",
    price: "790.00",
    color: "Black",
    badge: true,
    category: "Shoes",
    des: "Stylish block heel pumps for evening wear.",
  },
  {
    _id: 6014,
    img: bestSellerTwo,
    productName: "Merrell Moab 2",
    price: "890.00",
    color: "Brown",
    badge: false,
    category: "Shoes",
    des: "Hiking shoes with Vibram traction outsole.",
  },
  {
    _id: 6015,
    img: bestSellerThree,
    productName: "Jimmy Choo Sandals",
    price: "6950.00",
    color: "Nude",
    badge: true,
    category: "Shoes",
    des: "Luxury strappy sandals with crystal embellishments.",
  },
  {
    _id: 6016,
    img: bestSellerFour,
    productName: "Salomon Quest 4D 3 GTX",
    price: "1990.00",
    color: "Black",
    badge: true,
    category: "Shoes",
    des: "Advanced hiking boots with Gore-Tex membrane.",
  },

  // =================== MORE BOOKS ===================
  {
    _id: 7009,
    img: spfOne,
    productName: "The Subtle Art of Not Giving a F*ck",
    price: "169.00",
    color: "Paperback",
    badge: true,
    category: "Books",
    des: "Counterintuitive approach to living a good life.",
  },
  {
    _id: 7010,
    img: spfTwo,
    productName: "Educated",
    price: "159.00",
    color: "Hardcover",
    badge: false,
    category: "Books",
    des: "A memoir about a woman who grows up in a survivalist family.",
  },
  {
    _id: 7011,
    img: spfThree,
    productName: "The Alchemist",
    price: "129.00",
    color: "Paperback",
    badge: true,
    category: "Books",
    des: "A philosophical novel about following your dreams.",
  },
  {
    _id: 7012,
    img: spfFour,
    productName: "Atomic Habits",
    price: "189.00",
    color: "Hardcover",
    badge: true,
    category: "Books",
    des: "An easy and proven way to build good habits.",
  },
  {
    _id: 7013,
    img: bestSellerOne,
    productName: "The Midnight Library",
    price: "179.00",
    color: "Paperback",
    badge: false,
    category: "Books",
    des: "A novel about all the lives we could live.",
  },
  {
    _id: 7014,
    img: bestSellerTwo,
    productName: "Project Hail Mary",
    price: "169.00",
    color: "Hardcover",
    badge: true,
    category: "Books",
    des: "A lone astronaut must save humanity from extinction.",
  },
  {
    _id: 7015,
    img: bestSellerThree,
    productName: "The Seven Husbands of Evelyn Hugo",
    price: "159.00",
    color: "Paperback",
    badge: true,
    category: "Books",
    des: "A reclusive Hollywood icon tells her story.",
  },
  {
    _id: 7016,
    img: bestSellerFour,
    productName: "Where the Crawdads Sing",
    price: "149.00",
    color: "Paperback",
    badge: false,
    category: "Books",
    des: "A mystery wrapped in a coming-of-age story.",
  },
];


export const paginationItems = [...expandCategoryItems(convertProducts(basePaginationItems), 100)].reverse();
